[tool.poetry]
name = "eevee"
version = "0.2.4"
description = "Evaluation tools for internal projects"
authors = ["Abhinav Tushar <lepisma@fastmail.com>"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.2"
mypy = "^0.660.0"

[[tool.poetry.source]]
name = "cheeseshop"
url = "https://cheeseshop.vernacular.ai"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
